-- MySQL Script generated by MySQL Workbench
-- 05/26/17 21:11:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema webkoperasi
-- -----------------------------------------------------
-- Database koperasi tugas pemweb
DROP SCHEMA IF EXISTS `webkoperasi` ;

-- -----------------------------------------------------
-- Schema webkoperasi
--
-- Database koperasi tugas pemweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webkoperasi` DEFAULT CHARACTER SET utf8 ;
USE `webkoperasi` ;

-- -----------------------------------------------------
-- Table `webkoperasi`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`user` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(125) NULL,
  `password` VARCHAR(255) NULL,
  `level` VARCHAR(45) NULL COMMENT 'hak akses dari user, isinya admin atau member',
  `status` TINYINT(1) NULL DEFAULT 0 COMMENT 'status dari user. 0, nonaktif. 1, aktif.',
  `dibuat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'tanggal akun dibuat',
  `foto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webkoperasi`.`tipe_transaksi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`tipe_transaksi` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`tipe_transaksi` (
  `id_tipe_transaksi` INT NOT NULL AUTO_INCREMENT,
  `level` VARCHAR(45) NULL COMMENT 'level transaksi, admin / member',
  `kode_transaksi` VARCHAR(45) NULL,
  `kategori` VARCHAR(45) NULL COMMENT 'kategori berisi tabungan, angsuran, pinjaman, simpanan.',
  `nama` VARCHAR(125) NULL,
  `jumlah` INT NULL COMMENT 'jumlah uang',
  `maksimal` INT NULL COMMENT 'maksimal uang yang dapat dipinjam',
  `jatuh_tempo` INT NULL COMMENT 'lama jatuh tempo',
  `awal_bayar` INT NULL COMMENT 'tanggal dalam satu bulan',
  `akhir_bayar` INT NULL COMMENT 'tanggal dalam satu bulan',
  `keterangan` MEDIUMTEXT NULL,
  `bunga` DECIMAL(4,2) NULL COMMENT 'bunga pada pinjaman',
  `durasi` VARCHAR(45) NULL COMMENT 'durasi pembayaran, tiap minggu atau tiap bulan, dan seterusnya.',
  `id_tipe_transaksi_pinjaman` INT NULL COMMENT 'dipakai pada transaksi angsuran',
  PRIMARY KEY (`id_tipe_transaksi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webkoperasi`.`transaksi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`transaksi` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`transaksi` (
  `id_transaksi` INT NOT NULL AUTO_INCREMENT,
  `id_tipe_transaksi` INT NULL,
  `id_user` INT NULL,
  `metode` VARCHAR(45) NULL COMMENT 'Transfer/ Offline',
  `jumlah` INT NULL,
  `tanggal_transaksi` DATETIME NULL,
  `tanggal_verifikasi` DATETIME NULL,
  `dikirim` TINYINT(1) NULL DEFAULT 0 COMMENT 'dikirim setorannya. 0, belum. 1, sudah.',
  `catatan` TINYTEXT NULL,
  `kode` VARCHAR(5) NULL COMMENT 'kode pada berita transfer, random sebanyak 5 digit',
  `status` VARCHAR(45) NULL COMMENT 'status transaksi, pending / sukses',
  PRIMARY KEY (`id_transaksi`),
  INDEX `fk_id_user_transaksi_idx` (`id_user` ASC),
  INDEX `fk_id_tipe_transaksi_idx` (`id_tipe_transaksi` ASC),
  CONSTRAINT `fk_id_user_transaksi`
    FOREIGN KEY (`id_user`)
    REFERENCES `webkoperasi`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_tipe_transaksi`
    FOREIGN KEY (`id_tipe_transaksi`)
    REFERENCES `webkoperasi`.`tipe_transaksi` (`id_tipe_transaksi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webkoperasi`.`simpanan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`simpanan` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`simpanan` (
  `id_simpanan` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_transaksi` INT NULL,
  `id_user` INT NULL,
  `tipe_simpanan` VARCHAR(45) NULL,
  `tanggal` DATETIME NULL,
  `saldo` INT UNSIGNED NULL,
  PRIMARY KEY (`id_simpanan`),
  INDEX `fk_id_user_idx` (`id_user` ASC),
  INDEX `fk_id_transaksi_simpanan_idx` (`id_transaksi` ASC),
  CONSTRAINT `fk_id_user_simpanan`
    FOREIGN KEY (`id_user`)
    REFERENCES `webkoperasi`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_transaksi_simpanan`
    FOREIGN KEY (`id_transaksi`)
    REFERENCES `webkoperasi`.`transaksi` (`id_transaksi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webkoperasi`.`pinjaman`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`pinjaman` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`pinjaman` (
  `id_pinjaman` INT NOT NULL AUTO_INCREMENT,
  `id_transaksi` INT NULL,
  `id_user` INT NULL,
  `tipe_pinjaman` VARCHAR(45) NULL,
  `tanggal` DATETIME NULL,
  `jumlah_pinjaman` INT UNSIGNED NULL,
  `status_pinjaman` VARCHAR(45) NULL COMMENT 'status berisi lunas atau belum lunas',
  PRIMARY KEY (`id_pinjaman`),
  INDEX `fk_id_user_pinjaman_idx` (`id_user` ASC),
  INDEX `fk_id_transaksi_pinjaman_idx` (`id_transaksi` ASC),
  CONSTRAINT `fk_id_user_pinjaman`
    FOREIGN KEY (`id_user`)
    REFERENCES `webkoperasi`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_transaksi_pinjaman`
    FOREIGN KEY (`id_transaksi`)
    REFERENCES `webkoperasi`.`transaksi` (`id_transaksi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webkoperasi`.`angsuran`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`angsuran` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`angsuran` (
  `id_angsuran` INT NOT NULL AUTO_INCREMENT,
  `id_pinjaman` INT NULL,
  `id_transaksi` INT NULL,
  `id_user` INT NULL,
  `tanggal` DATETIME NULL,
  `jumlah_angsuran` INT NULL,
  `status_angsuran` VARCHAR(45) NULL,
  PRIMARY KEY (`id_angsuran`),
  INDEX `fk_id_user_angsuran_idx` (`id_user` ASC),
  INDEX `fk_id_pinjaman_idx` (`id_pinjaman` ASC),
  INDEX `fk_id_transaksi_idx` (`id_transaksi` ASC),
  CONSTRAINT `fk_id_user_angsuran`
    FOREIGN KEY (`id_user`)
    REFERENCES `webkoperasi`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_pinjaman`
    FOREIGN KEY (`id_pinjaman`)
    REFERENCES `webkoperasi`.`pinjaman` (`id_pinjaman`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_transaksi`
    FOREIGN KEY (`id_transaksi`)
    REFERENCES `webkoperasi`.`transaksi` (`id_transaksi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webkoperasi`.`tabungan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`tabungan` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`tabungan` (
  `id_tabungan` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `id_transaksi` INT NULL,
  `tipe_tabungan` VARCHAR(45) NULL,
  `tanggal` DATETIME NULL COMMENT 'tanggal transaksi di tabungan',
  `debit` INT NULL,
  `kredit` INT NULL,
  `saldo` INT NULL,
  PRIMARY KEY (`id_tabungan`),
  UNIQUE INDEX `id_tabungan_UNIQUE` (`id_tabungan` ASC),
  INDEX `fk_id_user_tabungan_idx` (`id_user` ASC),
  INDEX `fk_id_transaksi_tabungan_idx` (`id_transaksi` ASC),
  CONSTRAINT `fk_id_user_tabungan`
    FOREIGN KEY (`id_user`)
    REFERENCES `webkoperasi`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_transaksi_tabungan`
    FOREIGN KEY (`id_transaksi`)
    REFERENCES `webkoperasi`.`transaksi` (`id_transaksi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webkoperasi`.`profil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`profil` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`profil` (
  `nama_koperasi` VARCHAR(45) NULL,
  `logo` VARCHAR(45) NULL,
  `telepon` VARCHAR(45) NULL,
  `alamat1` VARCHAR(45) NULL,
  `alamat2` VARCHAR(45) NULL,
  `kode_pos` VARCHAR(45) NULL,
  `hp` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `latitude` VARCHAR(45) NULL,
  `bank` VARCHAR(45) NULL,
  `rekening` VARCHAR(45) NULL,
  `hari_buka` VARCHAR(45) NULL,
  `jam_buka` VARCHAR(45) NULL,
  `jam_tutup` VARCHAR(45) NULL,
  `menejer` VARCHAR(125) NULL,
  `slogan` VARCHAR(255) NULL,
  `visi` TINYTEXT NULL,
  `misi` MEDIUMTEXT NULL,
  `deskripsi` VARCHAR(45) NULL,
  `email` VARCHAR(125) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webkoperasi`.`detail_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`detail_user` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`detail_user` (
  `id_user` INT NOT NULL,
  `nama_depan` VARCHAR(45) NULL,
  `nama_belakang` VARCHAR(45) NULL,
  `jenis_kelamin` ENUM('Laki-laki', 'Perempuan') NULL,
  `tempat_lahir` VARCHAR(45) NULL,
  `tgl_lahir` VARCHAR(45) NULL,
  `alamat1` VARCHAR(45) NULL,
  `alamat2` VARCHAR(45) NULL,
  `kecamatan` VARCHAR(45) NULL,
  `kabupaten` VARCHAR(45) NULL,
  `provinsi` VARCHAR(45) NULL,
  `kode_post` VARCHAR(45) NULL,
  `telepon` VARCHAR(45) NULL,
  `hp` VARCHAR(45) NULL,
  `nomer_KTP` VARCHAR(45) NULL COMMENT 'Nomer KTP',
  `penghasilan` INT NULL COMMENT 'penghasilan perbulan',
  `nama_ibu` VARCHAR(255) NULL,
  `bank` VARCHAR(45) NULL,
  `rekening` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC),
  CONSTRAINT `fk_id_user_detail`
    FOREIGN KEY (`id_user`)
    REFERENCES `webkoperasi`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webkoperasi`.`keuangan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`keuangan` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`keuangan` (
  `id_keuangan` INT NOT NULL AUTO_INCREMENT,
  `id_transaksi` INT NULL,
  `tanggal` DATETIME NULL,
  `debit` INT NULL,
  `kredit` INT NULL,
  `saldo` INT NULL,
  PRIMARY KEY (`id_keuangan`),
  INDEX `fk_id_transaksi_keuangan_idx` (`id_transaksi` ASC),
  CONSTRAINT `fk_id_transaksi_keuangan`
    FOREIGN KEY (`id_transaksi`)
    REFERENCES `webkoperasi`.`transaksi` (`id_transaksi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webkoperasi`.`kontak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`kontak` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`kontak` (
  `id_kontak` INT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `subjek` VARCHAR(255) NULL,
  `isi` MEDIUMTEXT NULL,
  PRIMARY KEY (`id_kontak`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `webkoperasi`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `webkoperasi`;
INSERT INTO `webkoperasi`.`user` (`id_user`, `username`, `password`, `level`, `status`, `dibuat`, `foto`) VALUES (1, 'admin', 'admin123', 'admin', 1, NULL, NULL);
INSERT INTO `webkoperasi`.`user` (`id_user`, `username`, `password`, `level`, `status`, `dibuat`, `foto`) VALUES (2, 'member', 'member123', 'member', 1, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `webkoperasi`.`tipe_transaksi`
-- -----------------------------------------------------
START TRANSACTION;
USE `webkoperasi`;
INSERT INTO `webkoperasi`.`tipe_transaksi` (`id_tipe_transaksi`, `level`, `kode_transaksi`, `kategori`, `nama`, `jumlah`, `maksimal`, `jatuh_tempo`, `awal_bayar`, `akhir_bayar`, `keterangan`, `bunga`, `durasi`, `id_tipe_transaksi_pinjaman`) VALUES (1, 'Member', 'SM', 'Simpanan', 'Simpanan Wajib', 50000, NULL, 5, 1, 10, 'Pembayaran wajib tiap bulan bagi member koperasi', NULL, 'Bulan', NULL);
INSERT INTO `webkoperasi`.`tipe_transaksi` (`id_tipe_transaksi`, `level`, `kode_transaksi`, `kategori`, `nama`, `jumlah`, `maksimal`, `jatuh_tempo`, `awal_bayar`, `akhir_bayar`, `keterangan`, `bunga`, `durasi`, `id_tipe_transaksi_pinjaman`) VALUES (2, 'Member', 'SM', 'Simpanan', 'Simpanan Pokok', 100000, NULL, NULL, NULL, NULL, 'Pembayaran bagi member baru', NULL, NULL, NULL);
INSERT INTO `webkoperasi`.`tipe_transaksi` (`id_tipe_transaksi`, `level`, `kode_transaksi`, `kategori`, `nama`, `jumlah`, `maksimal`, `jatuh_tempo`, `awal_bayar`, `akhir_bayar`, `keterangan`, `bunga`, `durasi`, `id_tipe_transaksi_pinjaman`) VALUES (3, 'Member', 'PM', 'Pinjaman', 'Pinjaman Usaha Mikro', NULL, 5000000, NULL, NULL, NULL, 'Peminjaman untuk usaha mikro', 00.02, NULL, NULL);
INSERT INTO `webkoperasi`.`tipe_transaksi` (`id_tipe_transaksi`, `level`, `kode_transaksi`, `kategori`, `nama`, `jumlah`, `maksimal`, `jatuh_tempo`, `awal_bayar`, `akhir_bayar`, `keterangan`, `bunga`, `durasi`, `id_tipe_transaksi_pinjaman`) VALUES (4, 'Member', 'PM', 'Pinjaman', 'Pinjaman Kilat', NULL, 1000000, NULL, NULL, NULL, 'Pinjaman cepat', 00.05, NULL, NULL);
INSERT INTO `webkoperasi`.`tipe_transaksi` (`id_tipe_transaksi`, `level`, `kode_transaksi`, `kategori`, `nama`, `jumlah`, `maksimal`, `jatuh_tempo`, `awal_bayar`, `akhir_bayar`, `keterangan`, `bunga`, `durasi`, `id_tipe_transaksi_pinjaman`) VALUES (5, 'Member', 'AM', 'Angsuran', 'Angsuran Normal', 425000, NULL, 5, 10, 20, 'Angsuran normal', NULL, 'Bulan', 4);
INSERT INTO `webkoperasi`.`tipe_transaksi` (`id_tipe_transaksi`, `level`, `kode_transaksi`, `kategori`, `nama`, `jumlah`, `maksimal`, `jatuh_tempo`, `awal_bayar`, `akhir_bayar`, `keterangan`, `bunga`, `durasi`, `id_tipe_transaksi_pinjaman`) VALUES (6, 'Member', 'TM', 'Tabungan', 'Tabungan Suka-suka', NULL, NULL, NULL, NULL, NULL, 'Tabungan Suka-suka', NULL, NULL, NULL);
INSERT INTO `webkoperasi`.`tipe_transaksi` (`id_tipe_transaksi`, `level`, `kode_transaksi`, `kategori`, `nama`, `jumlah`, `maksimal`, `jatuh_tempo`, `awal_bayar`, `akhir_bayar`, `keterangan`, `bunga`, `durasi`, `id_tipe_transaksi_pinjaman`) VALUES (7, 'Member', 'TM', 'Tabungan', 'Tabungan Haji Reguler', 150000, NULL, 10, 5, 10, 'Tabungan Haji', NULL, 'Bulan', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `webkoperasi`.`detail_user`
-- -----------------------------------------------------
START TRANSACTION;
USE `webkoperasi`;
INSERT INTO `webkoperasi`.`detail_user` (`id_user`, `nama_depan`, `nama_belakang`, `jenis_kelamin`, `tempat_lahir`, `tgl_lahir`, `alamat1`, `alamat2`, `kecamatan`, `kabupaten`, `provinsi`, `kode_post`, `telepon`, `hp`, `nomer_KTP`, `penghasilan`, `nama_ibu`, `bank`, `rekening`) VALUES (1, 'Hasan', 'Mangrove', 'Laki-laki', 'Blitar', '27-06-1996', 'Jl. Masjid Baitul Makmur', '01/07 Tumpang', 'Talun', 'Blitar', 'Jawa Timur', '66183', NULL, '085745462845', '613814598826197', NULL, NULL, NULL, NULL);
INSERT INTO `webkoperasi`.`detail_user` (`id_user`, `nama_depan`, `nama_belakang`, `jenis_kelamin`, `tempat_lahir`, `tgl_lahir`, `alamat1`, `alamat2`, `kecamatan`, `kabupaten`, `provinsi`, `kode_post`, `telepon`, `hp`, `nomer_KTP`, `penghasilan`, `nama_ibu`, `bank`, `rekening`) VALUES (2, 'Iffah', 'Syarifah', 'Perempuan', 'Blitar', '12-12-1999', 'Jl. Suka Maju No. 40', '01/02 Gejayan', 'Kanigoro', 'Blitar', 'Jawa Timur', '66190', NULL, '086763274153', '9814t8896149899', NULL, NULL, NULL, NULL);

COMMIT;

