-- MySQL Script generated by MySQL Workbench
-- 05/23/17 13:48:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema webkoperasi
-- -----------------------------------------------------
-- Database koperasi tugas pemweb
DROP SCHEMA IF EXISTS `webkoperasi` ;

-- -----------------------------------------------------
-- Schema webkoperasi
--
-- Database koperasi tugas pemweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webkoperasi` DEFAULT CHARACTER SET utf8 ;
USE `webkoperasi` ;

-- -----------------------------------------------------
-- Table `webkoperasi`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`user` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`user` (
  `id_user` INT UNSIGNED NOT NULL,
  `username` VARCHAR(125) NULL,
  `password` VARCHAR(255) NULL,
  `level` VARCHAR(45) NULL COMMENT 'hak akses dari user, isinya admin atau member',
  `status` TINYINT(1) NULL DEFAULT 0 COMMENT 'status dari user. 0, nonaktif. 1, aktif.',
  `dibuat` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'tanggal akun dibuat',
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webkoperasi`.`jenis_simpanan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`jenis_simpanan` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`jenis_simpanan` (
  `id_jenis_simpanan` INT NOT NULL,
  `nama` VARCHAR(45) NULL,
  `jumlah_setoran` INT NULL,
  `deskripsi` TINYTEXT NULL,
  `mulai_pembayaran` DATE NULL COMMENT 'untuk simpanan wajib',
  `akhir_pembayaran` DATE NULL COMMENT 'untuk simpanan wajib',
  PRIMARY KEY (`id_jenis_simpanan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webkoperasi`.`simpanan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`simpanan` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`simpanan` (
  `id_simpanan` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_user` INT UNSIGNED NOT NULL,
  `id_jenis_simpanan` INT NULL COMMENT 'Tipe simpanan, Wajib dan Pokok',
  `tanggal` DATETIME NULL,
  `jumlah_setoran` INT UNSIGNED NULL,
  PRIMARY KEY (`id_simpanan`),
  INDEX `fk_id_user_idx` (`id_user` ASC),
  INDEX `fk_id_jenis_simpanan_idx` (`id_jenis_simpanan` ASC),
  CONSTRAINT `fk_id_user_simpanan`
    FOREIGN KEY (`id_user`)
    REFERENCES `webkoperasi`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_jenis_simpanan`
    FOREIGN KEY (`id_jenis_simpanan`)
    REFERENCES `webkoperasi`.`jenis_simpanan` (`id_jenis_simpanan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webkoperasi`.`jenis_pinjaman`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`jenis_pinjaman` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`jenis_pinjaman` (
  `id_jenis_pinjaman` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(45) NULL,
  `maksimal` INT NULL COMMENT 'maksimal uang yang boleh dipinjam',
  `bunga` DECIMAL(3,2) NULL COMMENT 'dalam persen',
  `durasi_` INT NULL COMMENT 'dalam hari',
  `jatuh_tempo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_jenis_pinjaman`),
  UNIQUE INDEX `id_jenis_pinjaman_UNIQUE` (`id_jenis_pinjaman` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webkoperasi`.`pinjaman`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`pinjaman` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`pinjaman` (
  `id_pinjaman` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_jenis_pinjaman` INT UNSIGNED NULL,
  `id_user` INT UNSIGNED NULL,
  `tanggal` DATETIME NULL,
  `jumlah_pinjaman` INT UNSIGNED NULL,
  `status_pinjaman` VARCHAR(45) NULL COMMENT 'status berisi lunas atau belum lunas',
  PRIMARY KEY (`id_pinjaman`),
  UNIQUE INDEX `id_pinjaman_UNIQUE` (`id_pinjaman` ASC),
  INDEX `fk_id_user_pinjaman_idx` (`id_user` ASC),
  INDEX `fk_id_jenis_pinjaman_idx` (`id_jenis_pinjaman` ASC),
  CONSTRAINT `fk_id_user_pinjaman`
    FOREIGN KEY (`id_user`)
    REFERENCES `webkoperasi`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_jenis_pinjaman`
    FOREIGN KEY (`id_jenis_pinjaman`)
    REFERENCES `webkoperasi`.`jenis_pinjaman` (`id_jenis_pinjaman`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webkoperasi`.`angsuran`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`angsuran` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`angsuran` (
  `id_angsuran` INT NOT NULL,
  `id_pinjaman` INT UNSIGNED NOT NULL,
  `id_user` INT UNSIGNED NOT NULL,
  `tanggal` DATETIME NULL,
  `jumlah_angsuran` INT UNSIGNED NOT NULL,
  `status_angsuran` VARCHAR(45) NULL,
  PRIMARY KEY (`id_angsuran`),
  INDEX `fk_id_user_angsuran_idx` (`id_user` ASC),
  INDEX `fk_id_pinjaman_idx` (`id_pinjaman` ASC),
  CONSTRAINT `fk_id_user_angsuran`
    FOREIGN KEY (`id_user`)
    REFERENCES `webkoperasi`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_pinjaman`
    FOREIGN KEY (`id_pinjaman`)
    REFERENCES `webkoperasi`.`pinjaman` (`id_pinjaman`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webkoperasi`.`tabungan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`tabungan` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`tabungan` (
  `id_tabungan` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_user` INT UNSIGNED NULL,
  `tanggal` DATETIME NULL COMMENT 'tanggal transaksi di tabungan',
  `debit` INT NULL,
  `kredit` INT NULL,
  `saldo` INT NULL,
  PRIMARY KEY (`id_tabungan`),
  UNIQUE INDEX `id_tabungan_UNIQUE` (`id_tabungan` ASC),
  INDEX `fk_id_user_idx` (`id_user` ASC),
  CONSTRAINT `fk_id_user_tabungan`
    FOREIGN KEY (`id_user`)
    REFERENCES `webkoperasi`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webkoperasi`.`profil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`profil` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`profil` (
  `nama_koperasi` VARCHAR(45) NULL,
  `deskripsi` VARCHAR(45) NULL,
  `logo` VARCHAR(45) NULL,
  `telepon` VARCHAR(45) NULL,
  `alamat1` VARCHAR(45) NULL,
  `alamat2` VARCHAR(45) NULL,
  `kode_pos` VARCHAR(45) NULL,
  `hp` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webkoperasi`.`detail_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`detail_user` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`detail_user` (
  `id_user` INT UNSIGNED NOT NULL,
  `nama_depan` VARCHAR(45) NULL,
  `nama_belakang` VARCHAR(45) NULL,
  `jenis_kelamin` ENUM('Laki-laki', 'Perempuan') NULL,
  `tempat_lahir` VARCHAR(45) NULL,
  `tgl_lahir` VARCHAR(45) NULL,
  `alamat1` VARCHAR(45) NULL,
  `alamat2` VARCHAR(45) NULL,
  `kecamatan` VARCHAR(45) NULL,
  `kabupaten` VARCHAR(45) NULL,
  `provinsi` VARCHAR(45) NULL,
  `kode_post` VARCHAR(45) NULL,
  `telepon` VARCHAR(45) NULL,
  `hp` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  `nomer_KTP` VARCHAR(45) NULL COMMENT 'Nomer KTP',
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC),
  PRIMARY KEY (`id_user`),
  CONSTRAINT `fk_id_user_detail`
    FOREIGN KEY (`id_user`)
    REFERENCES `webkoperasi`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webkoperasi`.`keuangan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webkoperasi`.`keuangan` ;

CREATE TABLE IF NOT EXISTS `webkoperasi`.`keuangan` (
  `id_keuangan` INT NOT NULL AUTO_INCREMENT,
  `tanggal` DATETIME NULL,
  `debit` INT NULL,
  `kredit` INT NULL,
  `saldo` INT NULL,
  `tipe_transaksi` VARCHAR(45) NULL,
  `detail` VARCHAR(65) NULL,
  PRIMARY KEY (`id_keuangan`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `webkoperasi`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `webkoperasi`;
INSERT INTO `webkoperasi`.`user` (`id_user`, `username`, `password`, `level`, `status`, `dibuat`) VALUES (1, 'admin', 'admin123', 'admin', 1, NULL);
INSERT INTO `webkoperasi`.`user` (`id_user`, `username`, `password`, `level`, `status`, `dibuat`) VALUES (2, 'member', 'member123', 'member', 1, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `webkoperasi`.`detail_user`
-- -----------------------------------------------------
START TRANSACTION;
USE `webkoperasi`;
INSERT INTO `webkoperasi`.`detail_user` (`id_user`, `nama_depan`, `nama_belakang`, `jenis_kelamin`, `tempat_lahir`, `tgl_lahir`, `alamat1`, `alamat2`, `kecamatan`, `kabupaten`, `provinsi`, `kode_post`, `telepon`, `hp`, `foto`, `nomer_KTP`) VALUES (1, 'Hasan', 'Mangrove', 'Laki-laki', 'Blitar', '27-06-1996', 'Jl. Masjid Baitul Makmur', '01/07 Tumpang', 'Talun', 'Blitar', 'Jawa Timur', '66183', NULL, '085745462845', NULL, '613814598826197');
INSERT INTO `webkoperasi`.`detail_user` (`id_user`, `nama_depan`, `nama_belakang`, `jenis_kelamin`, `tempat_lahir`, `tgl_lahir`, `alamat1`, `alamat2`, `kecamatan`, `kabupaten`, `provinsi`, `kode_post`, `telepon`, `hp`, `foto`, `nomer_KTP`) VALUES (2, 'Iffah', 'Syarifah', 'Perempuan', 'Blitar', '12-12-1999', 'Jl. Suka Maju No. 40', '01/02 Gejayan', 'Kanigoro', 'Blitar', 'Jawa Timur', '66190', NULL, '086763274153', NULL, '9814t8896149899');

COMMIT;

